"""initial schema

Revision ID: 235074550aec
Revises: 
Create Date: 2026-08-15 17:51:21.298623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '235074550aec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('band',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('japanese_name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('label_en', sa.String(length=120), nullable=False),
    sa.Column('label_ja', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.Enum('official', 'manufacturer', 'retailer', 'secondhand', 'search', 'user_submitted', name='source_kind'), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('trust_priority', sa.Integer(), nullable=False),
    sa.Column('crawl_policy', sa.Enum('auto', 'search_discovery_only', 'manual_import_only', 'disabled', name='crawl_policy'), nullable=False),
    sa.Column('robots_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('catalog_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sa.String(length=300), nullable=False),
    sa.Column('japanese_name', sa.String(length=300), nullable=True),
    sa.Column('original_title', sa.String(length=500), nullable=True),
    sa.Column('translated_title', sa.String(length=500), nullable=True),
    sa.Column('translation_source', sa.String(length=60), nullable=True),
    sa.Column('character_ids', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('band_id', sa.Integer(), nullable=True),
    sa.Column('series', sa.String(length=300), nullable=True),
    sa.Column('item_type_id', sa.Integer(), nullable=True),
    sa.Column('manufacturer', sa.String(length=200), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('release_date_source', sa.String(length=120), nullable=True),
    sa.Column('release_date_confidence', sa.Float(), nullable=True),
    sa.Column('official_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('product_number', sa.String(length=120), nullable=True),
    sa.Column('data_completeness', sa.Float(), nullable=False),
    sa.Column('created_by', sa.String(length=30), nullable=False),
    sa.Column('updated_by', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['band_id'], ['band.id'], ),
    sa.ForeignKeyConstraint(['item_type_id'], ['item_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('japanese_name', sa.String(length=120), nullable=True),
    sa.Column('english_name', sa.String(length=120), nullable=True),
    sa.Column('aliases', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('band_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['band_id'], ['band.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('crawled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw_title', sa.String(length=500), nullable=True),
    sa.Column('raw_description', sa.String(), nullable=True),
    sa.Column('raw_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('raw_currency', sa.String(length=10), nullable=True),
    sa.Column('raw_images', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_html_hash', sa.String(length=64), nullable=True),
    sa.Column('parser_version', sa.String(length=30), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('etag', sa.String(length=200), nullable=True),
    sa.Column('last_modified', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_product_id', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sa.String(length=300), nullable=False),
    sa.Column('japanese_name', sa.String(length=300), nullable=True),
    sa.Column('character_ids', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('series', sa.String(length=300), nullable=True),
    sa.Column('item_type_id', sa.Integer(), nullable=True),
    sa.Column('manufacturer', sa.String(length=200), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('product_number', sa.String(length=120), nullable=True),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', 'merged', name='candidate_status'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.String(length=1000), nullable=True),
    sa.Column('accepted_catalog_item_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accepted_catalog_item_id'], ['catalog_item.id'], ),
    sa.ForeignKeyConstraint(['item_type_id'], ['item_type.id'], ),
    sa.ForeignKeyConstraint(['raw_product_id'], ['raw_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalog_item_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catalog_item_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=1000), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_item_url', sa.String(length=1000), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['catalog_item_id'], ['catalog_item.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalog_item_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catalog_item_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('source_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['catalog_item_id'], ['catalog_item.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catalog_item_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_item_id'], ['catalog_item.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catalog_item_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('owned', 'wishlist', 'not_owned', name='collection_status'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_source', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_item_id'], ['catalog_item.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('catalog_item_id')
    )
    op.create_table('duplicate_review_pair',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('matched_catalog_item_id', sa.Integer(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('match_reason', sa.String(length=300), nullable=True),
    sa.Column('status', sa.Enum('pending', 'same', 'different', name='duplicate_review_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ),
    sa.ForeignKeyConstraint(['matched_catalog_item_id'], ['catalog_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('duplicate_review_pair')
    op.drop_table('user_collection')
    op.drop_table('price_history')
    op.drop_table('catalog_item_source')
    op.drop_table('catalog_item_image')
    op.drop_table('candidate')
    op.drop_table('raw_product')
    op.drop_table('character')
    op.drop_table('catalog_item')
    op.drop_table('source')
    op.drop_table('item_type')
    op.drop_table('band')
    # ### end Alembic commands ###
